"""empty message

Revision ID: 193844686be3
Revises: 4bcc25e25532
Create Date: 2020-08-13 18:07:01.809623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193844686be3'
down_revision = '4bcc25e25532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=250), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
